/**
 * Error codes for the Notification module
 */
export enum NotificationErrorCode {
  // Notification errors
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_CREATE_FAILED = 'NOTIFICATION_CREATE_FAILED',
  NOTIFICATION_UPDATE_FAILED = 'NOTIFICATION_UPDATE_FAILED',
  NOTIFICATION_DELIVERY_FAILED = 'NOTIFICATION_DELIVERY_FAILED',

  // Rate limit errors
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_CHECK_FAILED = 'RATE_LIMIT_CHECK_FAILED',
  RATE_LIMIT_UPDATE_FAILED = 'RATE_LIMIT_UPDATE_FAILED',
  RATE_LIMIT_OVERRIDE_DISABLED = 'RATE_LIMIT_OVERRIDE_DISABLED',
  RATE_LIMIT_OVERRIDE_FAILED = 'RATE_LIMIT_OVERRIDE_FAILED',

  // Preference errors
  PREFERENCE_NOT_FOUND = 'PREFERENCE_NOT_FOUND',
  PREFERENCE_ALREADY_EXISTS = 'PREFERENCE_ALREADY_EXISTS',

  // Template errors
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_INVALID_CONTENT = 'TEMPLATE_INVALID_CONTENT',
  TEMPLATE_INVALID_SYNTAX = 'TEMPLATE_INVALID_SYNTAX',
  TEMPLATE_COMPILE_ERROR = 'TEMPLATE_COMPILE_ERROR',
  TEMPLATE_RENDER_ERROR = 'TEMPLATE_RENDER_ERROR',

  // Producer errors
  PRODUCER_FAILED = 'PRODUCER_FAILED',
}
